### ISSUE TITLE
GPU out of memory when testing on composite-1k

### ISSUE THREAD

**Issue by ntuLC** [Yaoyi-Li/GCA-Matting#5]
Hi Yaoyi, 

Thank you for your remarkable work! 

I noticed in the README it says that 8GB is needed when testing on conposite-1k dataset. However, when I run tests with a GPU with 11GB memory (RTX2080Ti), the program raised an out of memory error. So I want to ask that do I need to resize the image first before running or change the 'scale' option in the toml file? Thank you!

My testing dataset is generated by the `Composition_code.py` provided with the Adobe Image Matting dataset.

**Comment by ntuLC** [comment]
Issue closed since I have resolved the problem. Thanks!

**Comment by umiiwa** [comment]
> Issue closed since I have resolved the problem. Thanks!

Could you please tell me how you resolved the problem? I've encountered the same problem.
