### ISSUE TITLE
More specific description on train and test datasets

### ISSUE THREAD

**Issue by lfxx** [Yaoyi-Li/GCA-Matting#6]
Thanks for your awesome work.Now i want use my own datasets to train the model.When i am working on making datasets,i am confused on the datasets structure.When i read your code,i find these paths:
```
train_fg = "/home/liyaoyi/dataset/Adobe/all/fg"
train_alpha = "/home/liyaoyi/dataset/Adobe/all/alpha"
train_bg = "/home/liyaoyi/dataset/coco_bg"
test_merged = "/home/liyaoyi/dataset/Adobe/Combined_Dataset/Test_set/merged"
test_alpha = "/home/liyaoyi/dataset/Adobe/Combined_Dataset/Test_set/alpha_copy"
test_trimap = "/home/liyaoyi/dataset/Adobe/Combined_Dataset/Test_set/trimaps"
```
What are these paths mean?Could your upload some demo pictures to make these clearer?Hope for your kindly reply!@Yaoyi-Li

**Comment by Yaoyi-Li** [comment]
These are folders of the foreground image, background image, alpha (ground truth), merged image and trimap. You can just follow the data structure of  Adobe Image Matting Dataset to create your own dataset.

**Comment by lfxx** [comment]
> These are folders of the foreground image, background image, alpha (ground truth), merged image and trimap. You can just follow the data structure of Adobe Image Matting Dataset to create your own dataset.

Thanks for your reply.What if my image has one more persons,can those images be used to train model?if not,where should i modify the code?@Yaoyi-Li

**Comment by xiezhang666** [comment]
hi, Thanks for your reply.  I have one more question similar to lfxx.    
How to produce files in directory test_merged ( test_merged = "/home/liyaoyi/dataset/Adobe/Combined_Dataset/Test_set/merged" ).
 Could you share shell script  as the way  that you dealt with copy_testing_alpha.sh. 
Hope for your kindly reply!@Yaoyi-Li
